projectId=cdf-athena
datasetprojectId=cdf-athena
dataset=testbq_bqmt
directoryIdentifierValue=0APlTqXcellfAUk9PVA

fileIdentifierValue=13Apcw7ufhI722G7mBcMSiQzIEn-EieHO
tsvFileIdentifier=1zSQZYmo_yhS4-cLQcarF7A0BhddIL3cs
avroFileIdentifier=1LjcvOtmlqHFGZKq69_XWmBZWsA8FEN0N
textFileIdentifier=14iQRpM_ov3o6MYyksfyR3odE1CBsc2q5
xlsFileIdentifier=1d8GulezFVRNt4BhEfrOvAWgG2WEb3XfO
googleDriveSkipHeaderTrue=True
invalidFilter=&&%$%^&
format=csv
FilterValue= name contains 'sample'
FilterValue2= name contains 'TestFile'
sample.schema=[{"key":"id","value":"int"},\
{"key":"name","value":"string"},\
{"key":"address","value":"string"}]

Test.schema=[{"key":"name","value":"string"},\
{"key":"age","value":"int"},\
{"key":"address","value":"string"}]

bqFileIdentifierOutputFile=testData/BqValidationExpectedFiles/bqFileIdentifierExpectedFile
bqTsvFileIdentifierOutputFile=testData/BqValidationExpectedFiles/bqTsvFileIdentifierExpectedFile
bqTextFileIdentifierOutputFile=testData/BqValidationExpectedFiles/bqTextFileIdentifierExpectedFile
bqXlsFileIdentifierOutputFile=testData/BqValidationExpectedFiles/bqXlsFileIdentifierExpectedFile
bqSpreadsheetsFileIdentifierOutputFile=testData/BqValidationExpectedFiles/bqSpreadsheetsIdentifierExpectedFile
